### ISSUE TITLE
Entities/Resources should be RDF::Resources

### ISSUE THREAD

**Issue by no-reply** [ActiveTriples/ActiveTriples#100]
```ruby
a = ActiveTriples::Resource.new
a.resource? #=> false
```

This should be `true`, and `ActiveTriples::Resource` should mixin `RDF::Resource` along with (instead of?) `RDF::Value`.

**Comment by no-reply** [comment]
Starting work on this with #115 as a base. I'm expecting that we'll need to figure out some equality issues to get this done right.

**Comment by no-reply** [comment]
This is *mostly* resolved in #133, but I'm leaving it open because `Resource` is still not directly included and there's some sanity checking to do on the interface.

It's notable that there are no shared examples in `ruby-rdf/rdf-spec` for `RDF::Term` or `RDF::Resource`. Maybe the best next step is to add those and make sure that `RDFSource` handles compliance.

**Comment by no-reply** [comment]
`RDFSource` cannot be an `RDF::Term` or `RDF::Resource` due to `RDF::Statement`'s handling of `@object`. The result would be statements like:
`#<SourceWithCreator:0x007f2f3cd20060> <http://purl.org/dc/terms/relation> Tove Jansson. `

see: https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/model/statement.rb#L114-L115

**Comment by no-reply** [comment]
@gkellogg: I wonder what you think about the possibility of simply removing [L114](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/model/statement.rb#L114)? I think this would cause [`Term#to_term`](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Term#to_term-instance_method) to be called for `Term`s and `Resource`s.

**Comment by gkellogg** [comment]
That would cause @object to be set to Literal.new(@object), probably not what you want. Our test coverages should be pretty good, so you can always experiment.

**Comment by no-reply** [comment]
@gkellogg: I'm thinking all `Term` cases are caught by `Value` on the next line, yes?

I'm wary of unintended consequences, but the core `rdf` specs pass in https://github.com/ruby-rdf/rdf/pull/204; the tests for this library also pass on that branch.

**Comment by gkellogg** [comment]
No, I think this is fine, and simpler, on second look. I merged the change.

**Comment by no-reply** [comment]
:rocket:
