### ISSUE TITLE
Don't allow a property called "next" to be created

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#101]
next is a keyword so when you attempt to call it you'll get:
```
     SyntaxError:
       app/models/proxy_node.rb:14: void value expression
```

**Comment by no-reply** [comment]
Can't reproduce:  

```ruby
[1] pry()> DummyResource.property :next
[2] pry()> subject
# => #<DummyResource:0x3fbcfd4b298c(#<DummyResource:0x007f79fa965318>)>
[3] pry()> subject.next
# => [#<ActiveTriples::Resource:0x3fbcfce01ad4(#ActiveTriples::Resource:0x007f79f9c035a8>)>]
```

Can you clarify?

We're excluding methods defined on the class from property definition; do we need to exclude other classes of names? See:

https://github.com/ActiveTriples/ActiveTriples/blob/master/lib/active_triples/configurable.rb#L62

**Comment by no-reply** [comment]
oh, just realizing how interesting that output is... opening a couple of other issues based on this...

But here's a more correct try:

```ruby 
[2] pry(#<RSpec::ExampleGroups::ActiveTriplesResource::RdfSubject>)> DummyResource.property :next, :predicate => RDF::DC.relation
[3] pry()> subject.next
# => []
[4] pry()> subject.next = 'blah'
# => "blah"
[5] pry()> subject.dump :ttl
# => "\n [\n    a <http://example.org/SomeClass>;\n    <http://purl.org/dc/terms/relation> \"blah\"\n ] .\n"
```

**Comment by jcoyne** [comment]
```ruby
 class Foo < ActiveTriples::Resource
  property :next, predicate: RDF::DC.title

   def foo
     x = next
     puts "X is #{x}"
   end
 end
SyntaxError: (irb):6: void value expression
	from /Users/justin/.rbenv/versions/2.1.5/bin/irb:11:in `<main>'
```

**Comment by jcoyne** [comment]
It does work fine if you use `self.next`, so maybe this isn't an issue?

**Comment by no-reply** [comment]
Ah, got it.

You should also be able to do `get_values(:next)`. I'm definitely in favor of continuing to allow it.  We use `#begin` and `#end` in some classes at DPLA.
