### ISSUE TITLE
Resource-centric vs graph-centric in persistence/querying

### ISSUE THREAD

**Issue by mjsuhonos** [ActiveTriples/ActiveTriples#117]
Currently, ActiveTriples::Resource can accept an arbitrary RDF::Graph, including statements with a different (potentially completely unrelated) RDF subject.  Additionally, persistence is achieved through the `#persist!`, `#destroy` and `#reload` methods.  Together these seem to take a graph-centric view of how ActiveTriples should behave, but this seems disjoint with the resource/model-centric behaviour that ActiveModel intends to provide.  For example:

Both ActiveRecord and Mongoid (to name two) implement similar interfaces for persistence and querying:

Persistence:
* http://mongoid.org/en/mongoid/docs/persistence.html
* http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html

Querying:
* http://mongoid.org/en/mongoid/docs/querying.html
* http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html

In both AR and Mongoid, the CRUD operations are scoped on a resource (or corresponding class)-centric view of the domain model.  The ActiveTriples README currently states that ActiveTriples::Resources "**represent a node in an RDF graph, and its surrounding statements**", which implies a resource-centric promise in being "ActiveModel-like".

As we move toward abstracting persistence (and potentially, querying/filtering), I propose that we align ActiveTriples' interface more closely to the resource-centric behaviour of other ActiveModel gems.

**Comment by no-reply** [comment]
:+1: Resolving this tension between the Object model and the underlying Graphs seems like the most important work there is to do here.  

In my own mind, I'm starting to understand what we're working with as "RDF Sources", as described here: http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#change-over-time.  That shift is reflected in #115.  

I think a move to a more common persistence interface would be a major step forward. The starting point should be an analysis of which parts of the interface ActiveRecord and its kin map well to an understanding of an Object as an RDF Source (see: LDP's RESTful handling for guidance).  Then I would want to draw a line around the minimal interface *required* to have a functioning persistence strategy. https://github.com/ActiveTriples/ActiveTriples/tree/feature/persistence-strategies

**Comment by no-reply** [comment]
@jeremyf I'd appreciate any input on the relative value of `Active` as it relates to the interface defined here: http://mongoid.org/en/mongoid/docs/persistence.html

**Comment by dchandekstark** [comment]
FWIW, This also clearly relates to recent conversations about query patterns (graph vs. filter).  :+1: @no-reply @mjsuhonos on pushing forward to a resolution/clarification.

**Comment by mjsuhonos** [comment]
Most of the more abstract/common persistence methods are already essentially delegated to the given persistence strategy, which perhaps we could move outward to the Persistable interface instead.

- `#destroy`
- `#persisted?`
- `#reload` -> delegated but initializes @term_cache

The following **NEW** delegated methods would also be added:
- `#delete`
- `#destroyed?`
- `#touch`
- `#save`
- `#save!`

The special exception is `#persist!`, which has some additional (looks like blocking) logic.  I'm guessing this is probably tied to one of the current PersistenceStrategies (repository?).

The decisions I see here are whether the behaviour of `#persist!` is semantically the same as `#save!`, ie. if they are **NOT**:

1. `#persist!` persists all nodes in the graph (as presently)
2. `#save!` persists only the `RDFSource`, with additional behaviour (auto-saved relations, etc.) being PersistenceStrategy-dependent.

Personally I find the notion of `#persist!` causing a potentially unrelated RDFSource to *also* be persisted to be non-obvious and possibly confusing.  As well, it's possible that nodes in the graph that don't have corresponding RDFSource model definitions wouldn't be persisted at all.

I'd like to hear others' opinions on this particular point.

The other part to persistence would be the addition of class-level `#create/#create!` methods, which AFAICS basically wrap an initializer and then `#save/#save!` methods in sequence.  And then ActiveModel callbacks registered for `:destroy`, `:save` and `#create`.

**Comment by jeremyf** [comment]
@mjsuhonos I like your well articulated questions and responses. I do have a clarification to make.

`ActiveModel` has a [linter](http://api.rubyonrails.org/classes/ActiveModel/Lint/Tests.html#method-i-test_errors_aref) to validate the behavior of an `ActiveModel` compliant object.

* test_errors_aref
* test_model_naming
* test_persisted?
* test_to_key
* test_to_param
* test_to_partial_path

That is to achieve interoperability with ActionPack and other Rails type things. Lets consider this ActiveModel compliance level-0.

Mongoid, ActiveRecord, and I believe ActiveTriples::Resource conform to this. Likewise ActiveFedora.

Mongoid, ActiveFedora, and ActiveRecord have similar APIs for persistence, but that is a matter of ActiveFedora and Mongoid following ActiveRecord's lead. I don't know if I would consider ActiveFedora nor Mongoid's implementation as ActiveModel compliance level-1 or as ActiveRecord compliance level-0.

I believe more important than method names is @mjsuhonos followup: is `#persist!` and `#save!` semantically equivalent? I don't know these answers.

@no-reply I don't have enough background to chime in much more.

For my two cents, the less the API looks like ActiveRecord's persistence methods the happier I am. If we are looking to swap out persistence layers, I believe there would be an adapter to transform the Graph to the constituent records (perhaps modeled via ActiveRecord) but my intuition says you'll need a mapping layer to perform that translation.

**Comment by mjsuhonos** [comment]
Thanks @jeremyf -- That's a really useful way to understand how AM approaches interoperability.

> If we are looking to swap out persistence layers, I believe there would be an adapter to transform the Graph to the constituent records (perhaps modeled via ActiveRecord) but my intuition says you'll need a mapping layer to perform that translation.

Unless I'm mistaken, I believe this is the role of each PersistenceStrategy implementation; in the case of eg. Mongoid, the "mapping" is basically what I've done in Ladder with `#update_resource` and `#new_from_graph` (both of which are admittedly rather unwieldy).

The "job" of a PersistenceStrategy then, is to persist an RDF::Graph, something that RDF::Repository already does quite comprehensively.  So why would we want, say, a Mongoid persistence strategy when we can already persist to MongoDB using RDF::Repository?  In fact, why wouldn't we just implement everything as a native RDF.rb storage adapter directly?  (*NB: I'm thinking out loud a bit here, but I don't mean to be rhetorical.*)

> For my two cents, the less the API looks like ActiveRecord's persistence methods the happier I am.

Fair enough, and I'm not inclined to advocate for some sort of 'ActiveModel compliance level-1' interface in ActiveTriples if it doesn't really exist elsewhere.

Looking at it another way, the tension then is between:

1. ActiveTriples 'inside' another ActiveModel ODM/ORM to give it RDF functionality, eg. using ActiveTriples::Identifiable the way Ladder does with Mongoid.  The main problem with this being that model definitions are not portable across persistence implementations, eg. https://github.com/ladder/modsrdf vs. https://github.com/acoburn/modsrdf

2. ActiveTriples as a common way of modelling RDF resources, with persistence and querying abstracted and pluggable (as above).  The main problem with this being that it requires asking ActiveTriples to behave like both an RDF::Graph and a generic, simplified ORM/ODM at the same time.

Moving from AT::Resource using inheritance to AT::RDFSource using composition is certainly a step in the right direction.  Maybe a common approach isn't actually desirable and we need to support both for different use cases?

**Comment by no-reply** [comment]
The latest work on feature/persistence-strategies (c738602) means I'm finally ready to tackle this question properly.

> The ActiveTriples README currently states that ActiveTriples::Resources "represent a node in an RDF graph, and its surrounding statements", which implies a resource-centric promise in being "ActiveModel-like".

This is the issue I'm trying to address with the `RDFSource` concept.  Where "surrounding statements" was vague, I think with `RDFSource`, we can clarify:
  - An `RDFSource` models "a resource that may be said to have a state that can change over time". (http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#change-over-time); therefore:
    - it implements the `RDF::Resource`, delegating to either an `RDF::Node` or an `RDF::URI` as appropriate.
  - An `RDFSource` has an `RDF::Graph` (i.e. a [graph](http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#section-rdf-graph)) that represents its current state.
    - The "RDF Source" concept as described in _RDF 1.1 Concepts_ allows a source to contain more than one graph. Currently, it's not clear to me how to approach that in this (or any) context, so I'm not considering it yet.
  - Persistence constitutes syncing the in memory `RDF::Graph` with [dataset](http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#dfn-rdf-dataset). The dataset, in the context of a given `PersistenceStrategy`:
    - SHOULD persist the entire state of the `RDFSource` (i.e. the graph persisted to the dataset for a given `RDFSource` should be isomorphic to the one managed by `ActiveTriples`).
    - SHOULD retrieve the entire state of the `RDFSource` (i.e. the graph retrieved from the dataset for a given `RDFSource` should be isomorphic to the one managed by `ActiveTriples`).
    - MAY be an `RDF::Repository` / `RDF::Dataset`, but is not required to implement those interfaces; this is the abstraction provided by `PersistenceStrategy`
    - MAY support named graphs/contexts.

It's possible that those SHOULDs should become MUSTs, but this ties in with a debate that's ongoing surrounding LDP and Fedora 4.  While Fedora 4 is changing it's behavior to respond with errors when sending triples it will decline to store, I'm thinking a Fedora 4 persistence strategy may gain flexibility by allowing the `PersistenceStrategy` and the dataset to negotiate the allowable triples, rather than throwing errors at the `Persistable` layer if the `RDFSource`s graph isn't conforming.

So that's a brain dump. I'm going to try to sketch out the persistence methods required to do the above later today.

**Comment by terrellt** [comment]
So if I'm understanding right, an ActiveTriples::Resource is an object representation of a graph, a persistence strategy takes that representation's underlying graph and persists it in some way to a Dataset which is the thing that actually handles storing the graph in a persistent way?

So when are we renaming to DataMapperTriples?

**Comment by jeremyf** [comment]
DataMapperTriples :+1: 

<Begin Soap Box>
Because the ActiveRecord pattern is something I don't believe holds water for long-term data needs.

**Comment by no-reply** [comment]
...soon?

In case that was a serious question: in my understanding of the Active Record pattern, this still conforms. RDFSource still provides a persistence & properties interface.

**Comment by terrellt** [comment]
Earlier comment was somewhat tongue in cheek, apologies. =)

If my earlier understanding fits, then I'm :+1: to using that to refactor our strategy going forward. Regarding DataMapper/ActiveX, if we're smart about it I think the "Active" can be a layer 6 on layer 5 of mapping components.

**Comment by terrellt** [comment]
@no-reply So a question - is an RDFSource's resource typified by a single subject? Because we make that assumption, and I wonder if it's accurate

**Comment by dchandekstark** [comment]
@terrellt Can you expand b/c I wonder if that's a source of pain for me.

**Comment by terrellt** [comment]
@dchandekstark ...Maybe? ActiveTriples' `ActiveTriples::Resource` is basically a set of accessors on top of a graph which act on triples that are in the graph and have the subject it was initialized with. The documentation SOUNDS like that's the case - in that an RDFSource is for a Resource and a Resource is represented by an IRI (subject here.)

AT just kind of accepts graphs that have other subjects and persists it with the rest, but maybe that's not the right behavior?

**Comment by no-reply** [comment]
@terrellt: It sounds like you're suggesting that `ActiveTriples` should take the approach adopted by Fedora 4, and reject triples added to an RDFSource that don't have a shared subject.  I've discussed this at length on the Fedora Tech list: 

https://groups.google.com/forum/#!topic/fedora-tech/TzHBaqNVJpo 
https://groups.google.com/forum/#!topic/fedora-tech/LBnvq7Z8ZuE (this is an extreme specimen of mega-thread, it might be useful to skip the first 50 messages or so :smile:)

My sense is that (per the above) an `ActiveTriples::Resource` / `ActiveTriples::RDFSource` is a Resource (and therefore identified by a single URI or quantified by a bnode).  However, it is a resource with state, and its state may be represented by a graph containing arbitrary triples.  Limiting the scope would mean that we would need an additional layer of abstraction to be able to work with the `ldp:RDFSource`s managed by systems that don't have scope limits (e.g. Marmotta)--and it's not clear to me how we would square the divergent domain models.

**Comment by terrellt** [comment]
@no-reply Not really suggesting, just wondering what an accurate model of an RDFSource is. Managing the state seems like a reasonable use case.

**Comment by no-reply** [comment]
Gotcha. As the linked Fedora-tech threads show, this is something of a contentious issue.  The above is my current understanding & I'm hoping to talk it out a bit with folks during the LDP workshop tomorrow.

Either way, I think there's some more clarification necessary, beyond what has gone into #115 and is discussed here.  In practice `ParentStrategy` (which mocks current behavior for non-Repository and non-Fedora datastream/LDP items) makes an `RDFSource` a sub-resource of its parent--i.e. it represents the state of its source in the context of the parent. That seems okay to me at first glance, but it could use some formalizing and documentation.

@dchandekstark I'm also interested to hear more about what you're experiencing.

**Comment by dchandekstark** [comment]
@no-reply A useful supplement to this conversation would be additional examples in the test suite and in documentation.  My main issue in general is understanding at a concrete level how the software is expected to behave, and I have found the use of nested resources in particular to be frustrating via Term accessors (cf. #41, #42, and #120).

**Comment by no-reply** [comment]
@dchandekstark heard. `Term` (soon to be renamed) is absolutely under-documented, and some of the problems at play are worse than that.  I'm hopeful that we can get momentum to clean some of this up--and doing what I can.  Your efforts to document specifics are appreciated.

**Comment by elrayle** [comment]
@mjsuhonos Can you provide a one line description of each of the methods that you list?  This will help ensure that we are all interpreting these the same way.  As an example, I'll put in the first one.

#destroy - permanently delete rdf source from triple store and return deleted rdf source in an AT:Resource
#persisted?
#reload -> delegated but initializes @term_cache
The following NEW delegated methods would also be added:

#delete
#destroyed?
#touch
#save
#save!

**Comment by mjsuhonos** [comment]
Jumping back in -- it looks like I may have struck a nerve with this issue.

Further to the last comment from @elraye, I'm going to abandon my earlier proposals about modifying the `Persistable` interface in any particular way, in favour of implementation-specific `PersistenceStrategies` as @no-reply describes.

I'm still struggling with how this would behave in concrete terms; eg. would `PersistenceStrategy` methods be delegated to the underlying persistence implementation?  I think probably, which means portability/compatibility between strategies is limited to differences between how they implement `ActiveModel`.  Which is fine in my opinion, we wouldn't normally expect this anyway.

As to @terrellt's question:
> is an RDFSource's resource typified by a single subject? Because we make that assumption, and I wonder if it's accurate

I used to have a lot of uncertainty about this, but I'm now pretty strongly of the mind of saying yes, an `RDFSource` can make promises about a single `RDF::Resource` (I might call it the 'core object' or similar).  This doesn't preclude it from ALSO behaving like an `RDF::Graph` that contains a set of statements in which EITHER the subject OR the object is that `RDF::Resource`; i.e. directly-related objects.

In this way, an `RDFSource` would behave consistently with both `RDF::Graph` as well as `ActiveModel`, insofar as persistence is concerned.  I'm still working through what is meant by "the entire state" in @no-reply's [(very useful) specs](https://github.com/ActiveTriples/ActiveTriples/issues/117#issuecomment-94557079), but this seems like a reasonable solution to me.
