### ISSUE TITLE
Should an IRI be marshalled as a Resource?

### ISSUE THREAD

**Issue by dchandekstark** [ActiveTriples/ActiveTriples#119]
(FWIW I'm using AT 0.2.3)

When AT marshals a graph as a Resource, it treats an IRI which is the object of a statement in the graph also as a Resource.  I find this awkward because one is required to call `rdf_subject` on the resource to get the `RDF::URI`. 

Example:

```ruby
class Identifier < ActiveTriples::Resource
  configure type: Ddr::Vocab::PREMIS.Identifier
  property :scheme, predicate: Ddr::Vocab::PREMIS.hasIdentifierType
  property :value, predicate: Ddr::Vocab::PREMIS.hasIdentifierValue
end
```

```
>> i = Ddr::Identifiers::Identifier.new.tap do |id|
?>   id.scheme = RDF::Vocab::Identifiers.local
>>   id.value = "foo"
>> end
=> #<Ddr::Identifiers::Identifier type=<http://id.loc.gov/vocabulary/identifiers/local>, value="foo">
>> i.scheme.first
=> #<ActiveTriples::Resource:0x3fce6f700c74(default)>
>> i.scheme.first.rdf_subject
=> #<RDF::Vocabulary::Term:0x3fce6f570ad0 URI:http://id.loc.gov/vocabulary/identifiers/local>
```

This is not a blocker and I'm open to being instructed as to why it's done this way. :)  Just wondering ...

**Comment by terrellt** [comment]
@dchandekstark I'm not sure what version this got implemented in, but there's https://github.com/ActiveTriples/ActiveTriples/blob/master/spec/active_triples/resource_spec.rb#L537 if you don't want to cast to a resource.

**Comment by no-reply** [comment]
I think the answer to this is simply "yes"--that's the RDF model and, as a design goal, the fundamental utility of `ActiveTriples`.  An IRI denotes a Resource and the idea is to have access to relevant statements for that resource via the models.  Returning a URI sends you back to querying blindly.

As @terrellt notes, you can choose not to cast as an option on a given property.  That's a bit of a hack, though.  I think it would be better to try to give you what you want out of `RDF::URI` without the need to choose between seeing your object as a URI vs. a Resouce. 

`Resource` already implements much of the `RDF::Term` interface, and there's some work on the `RDFSource` branch that brings it closer.  Can you say a little bit about what `URIs` do that a `Resource` doesn't, for your use cases?

**Comment by no-reply** [comment]
@dchandekstark it's also worth noting that the range of `premis:hasIdentifierValue` is `xsd:string`, so you probably just want to use literal values instead of IRIs, anyhow.

See: http://id.loc.gov/ontologies/premis.html#hasIdentifierValue

**Comment by dchandekstark** [comment]
@terrellt @no-reply Re: `premis:hasIdentifierValue` I'm aware of that, yes.  And I understand in the RDF model that an IRI is a resource.  But a literal is also a resource, so I'm not exactly sure why an IRI would be treated differently here.  In any case, it feels unexpected for a property getter to return an RDF graph (i.e., AT::Resource) when the object of the statement is an IRI and not a node.  So I guess I'm talking less about the underlying RDF model (about which I am admittedly not well-versed) and more about how it feels to use ActiveTriples as, so to speak, a data mapping tool.

**Comment by no-reply** [comment]
I get where you're coming from, but there's really no way to distinguish between an IRI that can have properties, etc... and one that cannot, except to define it as an access pattern--which you can do, though I don't recommend it.

The problem that you're having is that the data you're storing and accessing has a different meaning than what you're trying to do with it.  

`_:myObject dce:identifier "http://example.org/moomin" .` means that `_:myObject` has an identifier `"http://example.org/moomin"`. `_:myObject dce:identifier <http://example.org/moomin> .` means that `_:myObject` has an identifier which is the resource denoted by `http://example.org/moomin`. This is the reason most "identifier" predicates have range specified as `rdf:Literal` or `xsd:string`.  

>  it feels unexpected for a property getter to return an RDF graph (i.e., AT::Resource) when the object of the statement is an IRI and not a node

I don't think I follow.  Returning `Resource`s is the basic functionality of the property getter, right?  There is some clarification to do surrounding the relationship to other `RDF.rb` types/interfaces, specifically `Graph`, that may be causing confusion here... some of this is in progress on various branches and issues.  But I guess what I'm wondering is what you *are* expecting from the property getter?

**Comment by dchandekstark** [comment]
OK, thanks @no-reply for bearing with me on this.  The practical issue regards using vocabulary terms.  In this specific case, referencing the AT::Resource class above, I am using the predicate `premis:hasIdentifierType` in a statement where the object is the vocabulary term having the URI `http://id.loc.gov/vocabulary/identifiers/local`.  So, the N-Triples serialization of an example Identifier resource looks like:

```
_:g70221576432340 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.loc.gov/premis/rdf/v1#Identifier> .
_:g70221576432340 <http://www.loc.gov/premis/rdf/v1#hasIdentifierValue> "foo" .
_:g70221576432340 <http://www.loc.gov/premis/rdf/v1#hasIdentifierType> <http://id.loc.gov/vocabulary/identifiers/local>
```

What I care about when using this data model is that I can find the "local" identifier (if present) -- i.e., an Identifier where the (first value of the) scheme property equals the URI <http://id.loc.gov/vocabulary/identifiers/local>, that is, the value of `RDF::Vocab::Identifiers.local`.  So, I would expect I can ask an Identifier "does your scheme (scheme.first) equal `RDF::Vocab::Identifiers.local`".  But I can't actually do that.

**Comment by no-reply** [comment]
Okay, that's helpful!

One of the design goals of `ActiveTriples` was to allow you to have free-flowing models for data from external sources. So following from your example:

```ruby
myIdentifier.scheme.each(&:fetch)
myIdentifier.scheme.map(&:rdf_label) # => ["Locally defined identifier"]
```

You can also use the generic `#set_value` and `#get_value`, or otherwise safely treat it as any other IRI/bnode in your data--modeled or not.  So, it's modeled as a `Resource` (transitioning to `RDFSource`) because, from the model's standpoint that's what it is; and AT want's to give you access to that.

The source of your pain is maybe that `Resource` doesn't behave sufficiently like a `RDF::Term`.  This is something I'm eager to fix (and there's WIP: https://github.com/ActiveTriples/ActiveTriples/pull/115).  The equality issue is particularly tough, since there's identity vs. state to sort out.  I wonder if it would help if something like this worked:

```ruby
source = Resource.new('http://example.org/moomin')
# Testing identity
source == RDF::URI('http://example.org/moomin') # => true
# Testing state
source.eql? RDF::URI('http://example.org/moomin') # => false
new_source = source.dup
source.eql? source # => true
new_source << some_statement
source.eql? new_source # => false (?)
```

I think the point is really that `ActiveTriples` is letting you down by distinguishing between an IRI (as an instance of `RDF::Term`) and a `Resource` in some ways.

I'm still a little confused the use of the `id:local` property as a `premis:hasIdentifierType` value but, assuming you mean what that says,the above should all apply.

**Comment by dchandekstark** [comment]
Thanks, @no-reply for entertaining my questions.  I see now about `premis:hasIdentifierType`, which has range `xsd:string`.  It's obviously not germane to this issue -- which can be closed if you like -- but are you thinking I should be using the literal "http://id.loc.gov/vocabulary/identifiers/local" or perhaps just "local"?  If so, I've clearly missed something by not RTFM. :)
