### ISSUE TITLE
RDF Source Equality

### ISSUE THREAD

**Issue by no-reply** [ActiveTriples/ActiveTriples#121]
Given the model for `RDFSource` outlined [here](https://github.com/ActiveTriples/ActiveTriples/issues/117#issuecomment-94557079), I have some questions about the best way to handle equality and comparison.  It seems to me that (beyond the static `equal?` Object identity comparison) we have three concepts of equality to contend with:
  - `RDF::Resource` identity
     - If one `RDFSource` has a URI, is `other` represented (or a lexical representation of) the same URI; ([`RDF::URI` equality](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/URI#%3D%3D-instance_method)).
     - If both `RDFSource`s are bnodes, do they have the same local id; ([`Node` equality](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Node#%3D%3D-instance_method)).
  - State equality, i.e. [`RDF::Graph` equality](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Graph#%3D%3D-instance_method); do the graphs representing the current state of the two objects have _exactly_ the same contents.
  - `RDF::Graph` isomorphism; do the graphs representing the current state of the two objects have the same meaning. (This might be termed *true* state equality, but it's too computationally costly to be the default).

My sense is that the right way forward (originally proposed in a [comment](https://github.com/ActiveTriples/ActiveTriples/issues/119#issuecomment-91070084) on #119) is:
  - `#==` deals with `RDF::Resource` identity
  - `#eql?` deals with state equality (i.e. `RDF::Graph#==`)
  - `#isomorphic_with?` deals with isomorphism
  - `#equal?`, as always, deals with Ruby `Object` identity

This question is a blocker for #100, since `RDF::Term` introduces several comparison methods.

**Comment by gkellogg** [comment]
This is similar to the notions of equality in RDF.rb for properly matching SPARQL semantics, and it mostly has to do with what you do with BNodes. The RDF::Node#eql? likely does what you want for this case, as does Node#==.

**Comment by jeremyf** [comment]
Pinging @dbrower

**Comment by no-reply** [comment]
Thanks @gkellogg. `Node#==` seems to do what I'm suggesting for the `#==` case, but I think I'm missing something about how it relates to the underlying `Graph`.

Pinging also @mjsuhonos, though I know he's busy with other things.

**Comment by gkellogg** [comment]
I'm not sure how useful graph equality is beyond if they're either the same graph or are isomorphic. Different graphs with same triples isn't generically useful; you need isomorphism.

**Comment by dbrower** [comment]
The isomorphism is what I would expect for equality. Yes, I see that it can be expensive to do. How often are graphs compared for equality?

**Comment by no-reply** [comment]
@dbrower in this case, it depends on how frequently we care whether object state has changed. Since the in-memory graph (plus the `#rdf_subject` URI, if any) is understood to be the canonical representation of the in-memory object, comparisons with other graphs could be frequent.

I think these comments have me thinking that isomorphism should be the default graph comparison. `RDFSource` associated graphs are likely to be relatively small in most cases.

**Comment by mjsuhonos** [comment]
I'm inclined to broadly agree with everything that's been said so far.  Some of the nuances between RDF::Graph equality and isomorphism are a bit beyond me, but from a persistence perspective (myself thinking on #117), I would expect isomorphism via `#eql?` to be the default, and state-level equality comparisons additional functionality, possible even `PersistenceStrategy`-dependent.

**Comment by no-reply** [comment]
This is resolved in #133 with a simplified "Term equality" approach at: https://github.com/ActiveTriples/ActiveTriples/pull/133/files#diff-e9939ce86c000df5686160af00e0c53fR122
