### ISSUE TITLE
Set configured type if it's not present

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#123]
https://github.com/ActiveTriples/ActiveTriples/blob/a5a52bdb37c6ce519571ab2660f3ffb7d3edbb9d/lib/active_triples/rdf_source.rb#L111

Can we change `type.empty?` to `!type.include?(self.class.type)`?

**Comment by no-reply** [comment]
Yes, I think that's slightly better.  That simple change doesn't break any tests.  If someone (you?) submits a PR that includes a regression test for it, I'd be :+1: to merge immediately.

**Comment by no-reply** [comment]
I think this is resolved in light of https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/rdf_source.rb#L111-L115

If that's wrong, please reopen.
