### ISSUE TITLE
Can Configuration::Reflection and NodeConfig be merged?

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#127]
I'm not totally sure they can, but it seems like we may have established two parallel pathways to configure AT.

**Comment by jcoyne** [comment]
I think it's just the name Reflection that I'm caught up on. @terrellt what do you think of renaming `Configuration::Reflection` to `Configuration::Item`

**Comment by no-reply** [comment]
This may be a good line to pursue. I've been wanting to rip up `NodeConfig` for a while, since it  has some AF baggage that's unnecessary here (e.g. indexing).

**Comment by terrellt** [comment]
@jcoyne Renaming seems reasonable.

**Comment by jcoyne** [comment]
@no-reply AF has its own subclass of NodeConfig, so we should be able to move that  out of AT and into AF

**Comment by terrellt** [comment]
I like the idea of a property configuration similar to https://github.com/OregonDigital/oregondigital_2/blob/69f55378f0406ec1da7862f8e7f7eb404797e45d/app/models/data_model.rb, but I'm biased.

**Comment by no-reply** [comment]
I'm not picky about the name. `Item` seems fine.  `Reflection` is maybe confusing, since it's used elsewhere in the codebase for a related but different(?) pattern.

> I like the idea of a property configuration similar to [@terrellt's code]

Make it happen, pal.

**Comment by terrellt** [comment]
It'll happen. One day.

**Comment by terrellt** [comment]
(That day will probably be the next OD2 sprint)

**Comment by jcoyne** [comment]
As far as I'm concerned this ticket is closed, anyone else have reason to keep it open?

**Comment by no-reply** [comment]
nope. good talk.
