### ISSUE TITLE
partial uri for subclass of a resource does not generate full uri

### ISSUE THREAD

**Issue by elrayle** [ActiveTriples/ActiveTriples#131]
See new test at the bottom of [resource_spec.rb](https://github.com/ActiveTriples/ActiveTriples/blob/bug_get_uri_fail_subresource/spec/active_triples/resource_spec.rb) that describes "sub classing resource".  DummyPrimaryResource which inherits directly from ActiveTriples::Resource passes.  DummySubResource which inherits from DummyPrimaryResource fails.

This is a change in behavior from 0.6 and 0.7.  

The code change that causes the failure is in configurable.rb

configurable at [0.7)(https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/configurable.rb]    (FAILS)
```
    def base_uri
      configuration[:base_uri]
    end
```

configurable at 0.6   (WORKS)
```
    def base_uri
      nil
    end
```

This change came in with https://github.com/ActiveTriples/ActiveTriples/pull/126.

**Comment by elrayle** [comment]
@terrellt What was the need for changing base_uri?

What you will see when the test fails is that base_uri = nil in method get_uri (in resource.rb) for the sub classing resource.

**Comment by elrayle** [comment]
Added test that shows that a subclass that overrides configuration works.

**Comment by elrayle** [comment]
Clarification, method base_uri returns nil at 0.6 and 0.7.  To stop the error at 0.7, base_uri has to return nil and the configure method has to be reverted to 0.6.  I am continuing to explore configuration.rb and configure method.

**Comment by no-reply** [comment]
@elrayle Configuration was significantly rewritten in 0.7.0, in part to allow configuration of multiple types.  I suppose it makes sense that configuration inheritance would have worked in previous versions, but I can't say that was ever considered a feature.

I'd suggest we begin by documenting which, if any, configuration properties *should* be inheritable.  Rather than reverting to the older approach, we can continue to rework configuration to look like we think it should in a 1.0.0 release.

**Comment by elrayle** [comment]
The [open annotation gem](https://github.com/ld4l/open_annotation_rdf) uses inheritance for rdf type and is broken by the move to 0.7.  I appreciate the addition of multiple type (thanks terrellt) and what it allowed us to do for pcdm.  I am hoping that in the absense of a type configuration that a class would continue to inherit it from the parent class.  I think this will be useful as we expand classes to implement more complex models from pcdm where type doesn't change in the subclass.

**Comment by no-reply** [comment]
:+1: 

I think #132 should help us nail down a more general approach to inheritance.  For now, I think we should aim to inherit property configuration ("Schema") and type.  If we can document and test those two, patching as necessary, that would be a step forward.

I'm marking this `help wanted`, and will assign it to myself if/when I can pick it up.  @elrayle if you (or anyone else) wants to pick this up, that would be great.

**Comment by elrayle** [comment]
I may be able to look at this next week.  I have my head down in solr right now.  So timing depends on how well this week goes.

**Comment by no-reply** [comment]
Collapsing this into #158
