### ISSUE TITLE
Look into callback behavior and Persist! method.

### ISSUE THREAD

**Issue by tpendragon** [ActiveTriples/ActiveTriples#135]
Right now `Persist!` has code that sets @persisting = true before and after calling callbacks, so that it won't try to re-persist if a callback runs it. This is probably not the right way to handle things.

**Comment by mjsuhonos** [comment]
Is the issue here to avoid (infinite) recursive calls to `#persist!`, ie. from within the callback?  Since we're delegating to `persistence_strategy` anyway, do we have a use case that requires this code in the first place?  Happy to work on this.

**Comment by no-reply** [comment]
The current state of this is described here: https://github.com/ActiveTriples/ActiveTriples/pull/228#issuecomment-237037294

**Comment by no-reply** [comment]
@tpendragon, @mjsuhonos, @elrayle: This diff is my latest attempt at removing automatic `#persist!` calls to support this issue: https://github.com/ActiveTriples/ActiveTriples/compare/966e27d...feature/remove-persisting-flag

I think this is basically the right way to go; continuing to evaluate the testing situation. This will definitely be a change for users, so I'm looking for early feedback.

**Comment by no-reply** [comment]
A new branch for this: https://github.com/ActiveTriples/ActiveTriples/compare/feature/remove-auto-persist
