### ISSUE TITLE
Evaluate the status of `Identifiable`

### ISSUE THREAD

**Issue by no-reply** [ActiveTriples/ActiveTriples#139]
`Identifiable` is a mixin that offers some of the `RDFSource` interface for other `ActiveModel` frameworks.  Given that `RDFSource` itself is now a mixin, we should consider whether there's a better approach and which, if any, parts of identifiable are still necessary.

We can close this ticket with full documentation for, and/or a refactoring of `Identifiable`.

**Comment by mjsuhonos** [comment]
`Ladder::Resource` currently depends on `Identifiable`, primarily using `#resource` as a proxy method for accessing `RDF::Graph` functionality (eg. `#dump`).

I'd be keen to identify a better approach that allows mixing in `RDFSource` directly, if possible.

**Comment by mjsuhonos** [comment]
Circling back around on this now.  Given where `RDFSource` is now and the move towards RDF.rb 2.0, I suggest deprecating `Identifiable` entirely; I don't think it provides any advantage over `RDFSource`.

**Comment by no-reply** [comment]
@tpendragon do you agree this is a good goal?

**Comment by jcoyne** [comment]
Wasn't this a thing for RDF datastreams in AF?

**Comment by no-reply** [comment]
Yes. The Q is whether `RDFDatastream` could `include ActiveTriples::RDFSource`, or whether `Identifiable` is still doing something unique.

**Comment by no-reply** [comment]
I think @tpendragon's updates to ActiveFedora clarify that this is still needed in that context. I'd still like to look for other patterns to support that, but I'm resolving this ticket.
