### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by no-reply** [ActiveTriples/ActiveTriples#14]
Add and document some core validation functionality.

**Comment by dchandekstark** [comment]
I am using Hydra::Validations -- at least to deal with validating lists of literals.

**Comment by no-reply** [comment]
The initial thinking behind this ticket was to create some core ActiveModel validations that apply to RDF.  At this point, with the SHACL work being carried on by the RDF Shapes WG, I think it's safe to close this.  When that is solid enough for a ruby-rdf implementation, we can add a validator that consumes shapes and applies them to `RDFSource` graphs.

cc: @chrpr
