### ISSUE TITLE
Sub-resources are persisted to parent no matter what. 

### ISSUE THREAD

**Issue by tpendragon** [ActiveTriples/ActiveTriples#143]
The culprit is: https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/relation.rb#L148-L151

The regression appeared here: https://github.com/ActiveTriples/ActiveTriples/commit/36be0dece87ee9f47bea3ad2499e18deb36622f6#diff-8f61654568db5b5ce50e047c8c58913cR153

Before it would only persist if that class was configured to persist to parent, now it persists always - since a previous line we set the persistence strategy to be "to parent" (and never change it back)

**Comment by terrellt** [comment]
This seems to be a problem with the persistence strategy not being a class-level concern. We can't ask how it's configured to be persisted, because it isn't configured.

**Comment by no-reply** [comment]
I'd like to take a closer look at this before merging. I have the sense that there's a more thorough solution here, and had some ideas floating around when this work started.  It may just be time to figure this out properly.

**Comment by terrellt** [comment]
Sounds good. We may want to consider yanking 0.8 and 0.8.1 in that case - deep RDF which persists to external repositories as individual nodes is totally broken this way.

**Comment by terrellt** [comment]
@no-reply I'm tempted to not use "set_persistence_strategy" and make it unable to be changed after instantiation.

**Comment by no-reply** [comment]
> make it unable to be changed after instantiation.

I'm not sure why you would want to do this. The way I was leaning is just for an instance to never change its own strategy. So a new instance built from a "parent's" graph gets `ParentStrategy` at initialization, but can easily be changed.

I think there may also be space for `#add_as_child_node` or something similar, which would clone the resource and persist it to parent. That would leave you two instances, the original and a new one persisted to the parent.  

Still thinking on this.

**Comment by no-reply** [comment]
A first step in fixing a solution for this is at: https://github.com/ActiveTriples/ActiveTriples/issues/186

From IRC:
> 10:13 AM <￼tjohnson> i think with the proposed changeset, there are a couple of remaining questions about the "child node" concept and `ParentStrategy`
> 10:13 AM <￼tjohnson> first: when setting a value, when do you add the value's whole graph to the parent, and when do you just want the statement? Should this be configured at the property level?
> 10:15 AM <￼tjohnson> second: when retrieving a value, how can client code say that it *doesn't* want a child node, but instead the independently persisting object (i.e. when should `#get_values` give us instances with persistence strategies other than `ParentStrategy`)

**Comment by no-reply** [comment]
Can we consolidate this into https://github.com/ActiveTriples/ActiveTriples/issues/198?
