### ISSUE TITLE
When using parent strategy a new object should not be persisted if the parent isn't

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#148]
regression introduced in  710ebd5178aec9a88ad57ae1b77b4cd1db41f5ac

**Comment by jcoyne** [comment]
Duplicate of #143

**Comment by jcoyne** [comment]
This seems to fix ActiveFedora https://travis-ci.org/projecthydra/active_fedora/builds/67405420

**Comment by no-reply** [comment]
Interesting. I'm worried about that. I have the sense that more is broken and/or backwards-incompatible in the `ParentStrategy` than just this.

#150 looks like a good change, though.
