### ISSUE TITLE
Design discussion for adding ability to generate a solr document from a resource

### ISSUE THREAD

**Issue by elrayle** [ActiveTriples/ActiveTriples#153]
This is a discussion of the design to add generation of solr documents to ActiveTriples.  The design works, but has room for improvement.  I am hoping to get feedback that will allow the design to move to a state that others are comfortable with this code becoming part of ActiveTriples.

# Current Implementation

## Solr Document Structure

Add the ability to generate a solr document from a resource.  Generated solr documents are structured similar to those generated by ActiveFedora.

Three parts are generated.

* based on property configurations, add property values as searchable, sortable, and/or tokenized fields with possible multiple values
* serialize properties in object_profile field
* allow for caller to supply a block that extends the solr document

## Current Code

Current code for full implementation.

* https://github.com/ActiveTriples/ActiveTriples/tree/v0.7.x_solr - changes to node_config.rb only to support solr propery configurations (i.e., :indexed, :sortable, :tokenize, :range, :multiple)
* https://github.com/elrayle/active_triples-solrizer - generates solr document and provides connections to solr for committing and querying

## Operational example

* https://github.com/ld4l/ore_rdf/tree/solrize

```
require 'ld4l/ore_rdf'

# create an in-memory repository
ActiveTriples::Repositories.add_repository :default, RDF::Repository.new

p = LD4L::FoafRDF::Person.new('p4')
agg = LD4L::OreRDF::CreateAggregation.call( :id=>'agg10', :title=>'My Resources', :description=>'Resources that I like', :owner=>p )

LD4L::OreRDF::AddAggregatedResource.call( agg,'http://exmple.org/resource_1')
LD4L::OreRDF::AddAggregatedResource.call( agg,'http://exmple.org/resource_2')
LD4L::OreRDF::AddAggregatedResource.call( agg,'http://exmple.org/resource_3')

LD4L::OreRDF::PersistAggregation.call(agg)

# Create solr document
solr_doc = agg.aggregation_resource.generate_solr_document

# Commit generated solr doc to Solr instance
ActiveTriples::Solrizer::SolrService.register
ActiveTriples::Solrizer::SolrService.add(solr_doc,:params=>{:commit=>true})
ActiveTriples::Solrizer::SolrService.commit
```

NOTE: 
* requires solr core to be setup
* example is using default solr url - http://localhost:8983/solr/

# Remaining Work

## Missing

* no tests for solr_service
* didn't copy query_builder code from active-fedora (NOTE: solr_service references some of this code)
* no tests for configuration
* serialization into object_profile does not use the serializable_hash method as I couldn't get it to work.  I used attributes method instead.  This does not include any triples that area not part of the properties for the resource.  I did not look closely into why this wasn't working.  I'll take another look at it to see if I can be more specific.
* load_from_solr method that uses the existing object_profile and profile_indexing_service#import to create a new object with values loaded from solr instead of the triplestore

## Requirements to move to active_triples-solrizer gem into ActiveTriples

* resolve Missing from above
* move gem configuration from configuration.rb to the way it is done in ActiveTriples
* minor updates to solr_service.rb to get configurations from whereever ActiveTriples keeps them
* copy lib/solrizer directory to ActiveTriples/lib/active_triples and remove version.rb and cconfiguration.rb
* copy spec/solrizer directory to ActiveTriples/spec/active_triples/solrizer

**Comment by mjsuhonos** [comment]
:+1: for a active_triples-solrizer gem  to handle serializing/persisting ActiveTriples resources to solr

:-1: for moving it into ActiveTriples proper; I started down a similar path with ElasticSearch in https://github.com/ladder/active_triples-elasticsearch, and indexing requirements are IMO *far* too implementation-specific to require additional dependencies into the core gem.

**Comment by elrayle** [comment]
@mjsuhonos,  thanks for the feedback.

My inclination from the start was to have a separate gem.  Here is the sticking point... in order to drive the solr property fields from configurations on the property definitions, changes were made to ActiveTriples [node_config.rb](https://github.com/elrayle/ActiveTriples/blob/v0.7.x_solr/lib/active_triples/node_config.rb) ([diff](https://github.com/elrayle/ActiveTriples/commit/0ed9fb1e072d8fa7322ffc7cf97c4ff59918cb3f)).

Potential solutions:
* Option 1: View the additional property configurations as generally applicable to a number of indexing schemes and accept the changes to node_config.rb into ActiveTriples and leave the remainder of the code in the active_triples-solrizer gem  (current implementation)
* Option 2:  Explore ActiveTriples ability to allow configurations to be added to a property without being defined in advance.   I noticed that the initialize method for NodeConfig accepts a block. So perhaps there's a way to do this without modifying the ActiveTriples gem.

**Comment by jcoyne** [comment]
@elrayle ActiveFedora extends NodeConfig exactly as you need: https://github.com/projecthydra/active_fedora/blob/eb9bc665ed662f157368f56df57adf3b247193c4/lib/active_fedora/attributes/node_config.rb#L2

**Comment by elrayle** [comment]
@jcoyne Are you able to create a specific resource class (which uses the extended set of properties) from ActiveTriples::Resource (e.g. class DummyResource < ActiveTriples::Resource) and use the configurations on property definitions that you added to your version of NodeConfig?  I don't want DummyResource to have to inherit from an in between class that adds the extended configurations.

**Comment by elrayle** [comment]
## Observations

In exploring this further, I noticed method ActiveTriples::NodeConfig.with_index which appears to be related to similar work. It makes use of two additional configurations, data_type and behaviors.

* behaviors is defined as an attribute in ActiveTriples::NodeConfig, but is not given a default value in the initialize method.  It is also referenced in the with_index method and the related IndexObject class which is available through the yield block of the with_index method.
* data_type is not defined as an attribute, but is referenced in the with_index method and the related IndexObject class which is available through the yield block of the with_index method.

It does not appear that the with_index method is ever called within the normal operation of a resource that directly extends ActiveTriples::Resource.  Did I miss something?  It appears that ActiveFedora makes use of this for some of its classes that extend ActiveTriples::Resource functionality.  In that case, if I am interpreting things correctly, the end resource inherits from AcitveFedora classes instead of ActiveTriples classes.

## Proposed smaller code change to ActiveTriples::NodeConfig

I like the use of the simple set of configuration extensions (i.e., data_type and behaviors) that can be applied to various approaches to indexing.  Behaviors can hold all the various configuration extensions of a property for solrizing (e.g., sortable, range, multiple, etc.) and a different set for another approach (e.g., elastic search).  The set of behaviors would be defined by the gem making use of the behaviors, in this case active_triples-solrizer.

I propose to make a simple change that will make these usable from the active_triples-solrizer gem allowing resources to be directly created from ActiveTriples::Resource and still make use of the solrizer gem to create solr fields for properties with the data_type and behaviors property configurations.

* behaviors – give it a default value of an empty array in the initialize method
* data_type – define ti as an attribute and give it a default value of nil in the initialize method

See diff at...  https://github.com/elrayle/ActiveTriples/compare/v0.7.x...elrayle:v0.7.x_solr

This is a more generic change that should allow for extensions by any number of approaches to indexing.  @mjsuhonos would this address your concerns?

**Comment by no-reply** [comment]
Thanks @elrayle,

Many of the things you've noticed in `NodeConfig` are left over from the ActiveFedora 6 days; that code originated there, and was initially copied more or less wholesale.

I'm not in a good position to speak about the needs of `ActiveFedora`, here, but for this library's part my inclination would be to remove `#with_index` and `IndexObject` entirely and add a mechanism for extending `NodeConfig`. Then various extensions (index related and otherwise) could be added as method calls within the block.

Can you give an example of how indexing would look with your diff? It seems a departure from what we started with way back when, and I'm not totally sure I follow where you're going with it.  For context, the old style would have been something like:

```ruby
property :my_property, predicate: RDF::DC.title do |index|
   index.as :storable, :searchable, :blahblahblah
end
```

As a side note: I believe by the time this library broke from AF7, `data_type` was already ignored entirely, with values serializing based on the literal data type in the actual value.

Thanks for giving this your attention. I'm generally :+1: on any changes to `NodeConfig` that are AF-friendly, especially if they reduce its scope.

**Comment by jcoyne** [comment]
I'd be :+1: to moving the with_index stuff back into AF and removing it from AT.

**Comment by jcoyne** [comment]
@elrayle yes, you can add it to any AT class provided you don't use property (or override it) You will have to use a custom PropertyBuilder. See AF for the example of that.

**Comment by elrayle** [comment]
I made use of the syntax provided by @no-reply.  The completed gem, which requires no change to ActiveTriples, is located at...  https://github.com/ActiveTriples/active_triples-solrizer.

The README provides working examples.

Please do not remove the with_index code from ActiveTriples NodeConfig class.  The new active_triples-solrizer gem depends on this code to interact with ActiveTriples resources.

Feel free to make further comments on this design.  There are a few notes at the end of the README describing limitations of the current gem implementation.

**Comment by elrayle** [comment]
I will leave this issue open for approximately a week for further comments on the design.

**Comment by no-reply** [comment]
This looks great @elrayle! Thanks for putting it together.

Can you comment on the relationship between the `data_type` arguments and the typed data in individual values?  Do you stringify all values before indexing? If so, are you counting on the `Literal#to_s` to normalize in some way?

I ask in part because it may help me update and strengthen tests of behavior between `ActiveTriples::Relation` and `RDF::Literal`.

**Comment by elrayle** [comment]
I am guessing by 'typed data in individual values', you mean what I would get if I execute .class on the value?  Solrizer sets the type and it will guess the type automatically if you don't set type= on the property.  In ActiveTriples::Solrizer, it expects the type of the value to be correct for the data_type specified.  It isn't doing any error checking on this.  Solr doesn't care if you call it an integer and then store 'foo' in it, although I suspect things will get weird if you try to do searching expecting an integer.  In ActiveTriples::Solrizer, you can set `data_type=:guess` and it will use is_a? tests to guess the data type from the value.  It is a balancing act between flexibility and control.  The developer can decide which approach they prefer.

I do not stringify the values before indexing.  The solr doc is a hash where values may be strings, numeric, array, etc.  Stringify may happen later down in the code that I didn't write.  I didn't explore that deep since it just works ;) The last place that I deal with anything is in the add method that receives the solr doc hash as a parameter.  See around line 130 of https://github.com/ActiveTriples/active_triples-solrizer/blob/master/lib/active_triples/solrizer/solr_service.rb
