### ISSUE TITLE
Relation#set should avoid type checking

### ISSUE THREAD

**Issue by dchandekstark** [ActiveTriples/ActiveTriples#165]
As of 10/1/15:

```ruby
def set(values)
  values = values.to_a if values.is_a? Relation
  values = [values].compact unless values.kind_of?(Array)
  # snip   
end
```

Suggest:

```ruby
def set(values)
  vals = Array(values).compact
  # snip
end
```

Any reason that wouldn't work?

**Comment by jeremyf** [comment]
Favor `Array.wrap` over `Array`. See #178

**Comment by dchandekstark** [comment]
+1 @jeremyf

**Comment by no-reply** [comment]
Both 'Array()` and `Array.wrap()` fail some `RDF::List` related specs.

There's probably a better approach, here, but it's more complicated than the suggested solution accounts for.

I'm :+1: on stripping out type checks as much as possible, but I've looked at this three or four times, and I don't see a clear solution. PRs welcome.

**Comment by no-reply** [comment]
Closing this in lieu of a better suggestion.
