### ISSUE TITLE
Validations are broken

### ISSUE THREAD

**Issue by dchandekstark** [ActiveTriples/ActiveTriples#166]
At least in AT 0.7.1, validation callbacks are not run.  See https://github.com/dchandekstark/ActiveTriples/blob/validations-bug/spec/active_triples/validations_spec.rb.

**Comment by dchandekstark** [comment]
This seems to have been a false alarm.

**Comment by dchandekstark** [comment]
Still working on it.  There seems to be an issue with the order in which ActiveModel::Validations is included.  At the position it exists in 0.7.1, two of the tests added to #168 fail.  But it *doesn't* need to be moved inside the `included` block as originally proposed in #168.

**Comment by dchandekstark** [comment]
OK, I think I've got it now.  The problem is that RDFSource includes both `RDF::Enumerable` and `ActiveModels::Validations`, both of which provide `#valid?` and `#invalid?`.  In the include order of v0.7.1, I see this:

> ActiveTriples::Resource.ancestors
 => [ActiveTriples::Resource, ActiveTriples::RDFSource, ActiveModel::Serializers::JSON, ActiveModel::Serialization, RDF::Mutable, RDF::Writable, RDF::Readable, RDF::Queryable, RDF::Enumerable, RDF::Durable, RDF::Countable, Enumerable, RDF::Value, ActiveModel::Conversion, ActiveModel::Validations::HelperMethods, ActiveSupport::Callbacks, ActiveModel::Validations, ActiveTriples::Reflection, ActiveTriples::Resource::GeneratedPropertyMethods, ActiveTriples::Properties, ActiveTriples::NestedAttributes, Object, JSON::Ext::Generator::GeneratorMethods::Object, PP::ObjectMixin, Kernel, BasicObject] 

If I move `ActiveModel::Validations` to be the last included module (after `ActiveModel::Serializers::JSON`), I get this:

> ActiveTriples::Resource.ancestors
 => [ActiveTriples::Resource, ActiveTriples::RDFSource, ActiveModel::Validations::HelperMethods, ActiveSupport::Callbacks, ActiveModel::Validations, ActiveModel::Serializers::JSON, ActiveModel::Serialization, RDF::Mutable, RDF::Writable, RDF::Readable, RDF::Queryable, RDF::Enumerable, RDF::Durable, RDF::Countable, Enumerable, RDF::Value, ActiveModel::Conversion, ActiveTriples::Reflection, ActiveTriples::Resource::GeneratedPropertyMethods, ActiveTriples::Properties, ActiveTriples::NestedAttributes, Object, JSON::Ext::Generator::GeneratorMethods::Object, PP::ObjectMixin, Kernel, BasicObject] 

Obviously, the problem can also be solved by moving `include ActiveModel::Validations` inside the `included` block as proposed in #168.

/cc @gkellogg @no-reply @tpendragon @jcoyne @mjgiarlo

**Comment by no-reply** [comment]
That makes sense, and explains why the error doesn't pop up in 0.8, where this was explicitly patched and tested for. Looks like what we need is to backport this: https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/rdf_source.rb#L67-L72

**Comment by dchandekstark** [comment]
Excellent.  I'd be happy to amend #168 accordingly.  If that's OK, would love to see 0.7.2 soon.

**Comment by no-reply** [comment]
yeah. if you can get this going. I'll merge and release ASAP.

**Comment by no-reply** [comment]
Did we eventually get this patched in 0.7.x?

**Comment by dchandekstark** [comment]
0.7.2 works for me.

**Comment by no-reply** [comment]
:roller_coaster:
