### ISSUE TITLE
Property extending OpenStruct obliterates method cache

### ISSUE THREAD

**Issue by jeremyf** [ActiveTriples/ActiveTriples#177]
Switch ActiveTriples::Property to a custom class that does not extend OpenStruct.

> Ruby's OpenStruct class defines accessor methods dynamically when created. This means that the method caches are cleared every time an OpenStruct is instantiated:

https://github.com/charliesome/charlie.bz/blob/master/posts/things-that-clear-rubys-method-cache.md

**Comment by jcoyne** [comment]
Seems like a PORO would be just fine.  PR welcome.

**Comment by jeremyf** [comment]
Working on it. Need to get my dev environment working. But that requires
the Gemfile change from the other PR. I'll be working on that tomorrow.

Jeremy Friesen
