### ISSUE TITLE
Changes to `add_child_node` behavior?

### ISSUE THREAD

**Issue by no-reply** [ActiveTriples/ActiveTriples#186]
#184 deals with the problem of circularity in child nodes, but I want to propose a more radical change.

From the beginning, the default behavior when setting a `Resource`/`RDFSource` to a value has been to make the added instance a "child" of the target. So `subject.relation = other` sets  `other.parent` to `subject`. This leads to awkward state changes for the value resources, as a side effect of being set to a value.

I think we should remove this state change and set `#parent`/`ParentStrategy` only when accessing a child from within a parent's graph. For example:

```ruby
other << statement
subject.relation = other

# we still capture data when adding a node by default
# better configuration for this should be considered
subject.has_statement?(statement) # => true   

other.persistence_strategy # unchanged

subject.relation.first.persistence_stategy # => ParentStrategy
subject.relation.first.persistence_stategy.parent # => subject
subject.relation.first << new_statement
subject.relation.first.persist! # is this/should this be required?

subject.has_statement?(new_statement) # => true
other.has_statement?(new_statement) # => false
```

Something like change is represented here, with a couple of broken tests and a need to adjust node caching. https://github.com/ActiveTriples/ActiveTriples/tree/feature/no_child_capture

I haven't looked seriously at the effects of the caching behavior change, but I wanted to get a sense of how people feel about this change.  I think it would seriously simplify the `Relation` implementation/behavior.

**Comment by no-reply** [comment]
cc: @jcoyne @tpendragon @dchandekstark

**Comment by no-reply** [comment]
also cc: @elrayle

**Comment by tpendragon** [comment]
@no-reply What happens here:

```ruby
subject.relation.first == other
```

**Comment by no-reply** [comment]
`#==` tests [RDF Term equality](https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/rdf_source.rb#L113-L125) and would give `true`.

`#eql?` would give `false`.

**Comment by no-reply** [comment]
The pitfall here is that users would need to be conscious of their instances.  It would be normal to want `other` to fall out of scope and deallocate after setting it to a value.

Using `#build` or similar would save you the trouble of worrying about it.

**Comment by no-reply** [comment]
In #projecthydra IRC, @tpendragon said: 

> I guess it was mostly getting to a different point: if I mutate other after setting a child, does the child mutate?

I changed the example in the main issue text to show that it doesn't/shouldn't. The two instances now have distinct graphs.

**Comment by no-reply** [comment]
#188 is a potential implementation of these changes, for comment.
