### ISSUE TITLE
Dependencies conflict with Ruby version

### ISSUE THREAD

**Issue by elrayle** [ActiveTriples/ActiveTriples#225]
https://rubygems.org/gems/listen 3.1.2 and higher require Ruby 2.2.3.  To use earlier versions of Ruby requires pinning listen to 3.1.1.  

[active-triples.gemspec](https://github.com/ActiveTriples/ActiveTriples/blob/develop/active-triples.gemspec) states...
```
s.required_ruby_version = '>= 2.1.0'
```

[Travis config](https://github.com/ActiveTriples/ActiveTriples/blob/develop/.travis.yml) is set up to test... 2.1 and 2.2.4.  Not sure why 2.1 passes.  If we were testing 2.2.0-2.2.2, those would fail.

**Comment by elrayle** [comment]
@no-reply Can we update the required_ruby_version to 2.2.3?

**Comment by no-reply** [comment]
`ActiveTriples` doesn't have a dependency on `listen`. Is that coming in somewhere else for you?

I'd prefer to continue to support Ruby 2.1 and up. I understand this to be increasingly standard practice in the gem ecosystem.

**Comment by elrayle** [comment]
I took a fresh clone of ActiveTriples and ran the tests.  To run the ActiveTriples tests on my machine, I had to pin the following...

```
  s.add_dependency 'activesupport', '= 4.2.0'
  s.add_dependency('listen',"=3.1.1")
```

**Comment by elrayle** [comment]
This was using Ruby 2.2.2.

**Comment by no-reply** [comment]
Have you tried upgrading to [`bundler` 1.11.x](http://bundler.io/blog/2015/12/12/version-1-11-released.html#new-features)? This should resolve your gems by `required_ruby_version`.

**Comment by elrayle** [comment]
Bundler was the problem.  Thanks.

**Comment by no-reply** [comment]
Any time.

Unfortunately, this seems to be the status quo for gems depending on `activesupport` post Rails 5. On the plus side, the newest bundler versions handle it fine as long as we stay 4.2 compatible.

**Comment by elrayle** [comment]
From Travis...  test fails for 2.1.0

```
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.0.0), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.
```

@no-reply Had to reopen because the problem does still exist for any Ruby < 2.2.2.

**Comment by no-reply** [comment]
@elrayle can you link to a build where this fails? I don't see this in https://travis-ci.org/ActiveTriples/ActiveTriples/branches

**Comment by elrayle** [comment]
Reference:  https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

Based on this, it seems that it would be good to support 2.1.  ActiveSupport's latest version (5.0.0) won't work with it though.

**Comment by no-reply** [comment]
I'm not clear on what the current issue is. 

Travis looks happy, to me. We have [a pin in our Gemfile](https://github.com/ActiveTriples/ActiveTriples/blob/develop/Gemfile#L5), and `bundler` 1.11 resolves gem versions explictly to handle cases like this.

Locally, when I use Ruby 2.1 or 2.2, everything rewinds to ActiveSupport/ActiveModel 4.2 without any trouble.

Can you clarify?

**Comment by elrayle** [comment]
There must be something different in my local environment for AT.  I pushed a branch just to test ruby 2.1 and 2.2.2 and Travis was happy with both.

**Comment by no-reply** [comment]
:ok_hand: Do feel free to reopen if you figure out what's going on.

**Comment by elrayle** [comment]
FYI... the offending gem bringing in Listen 3.1.5 was guard-rspec.  This gem was in AT 0.8.2 gemspec, but not in AT 0.10.0.  So it was hanging around when I switched to the latest code causing problems on my local machine but for Travis.  I cleaned everything up locally and the dependency conflict is gone.
