### ISSUE TITLE
Term delegates too many methods

### ISSUE THREAD

**Issue by dchandekstark** [ActiveTriples/ActiveTriples#41]
I re-added :send to fix #39.  @jcoyne suggested using https://github.com/rails/rails/blob/08754f12e65a9ec79633a605e986d0f1ffa4b251/activerecord/lib/active_record/querying.rb#L3-L14 and https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/delegation.rb#L46 instead.

**Comment by dchandekstark** [comment]
A good start would be to document in spec tests what methods we really expect it to delegate to :result.

**Comment by dchandekstark** [comment]
Cf. #74

**Comment by no-reply** [comment]
This is closely related to the work needed to handle #120.  @terrellt, if you still plan to undertake that, can you make sure this issue gets considered?

**Comment by no-reply** [comment]
@dchandekstark If you have a minute, I'd like your feedback on #155, whether that resolves this adequately, and whether it should be ported back to `0.6.x` and `0.7.x`.

**Comment by dchandekstark** [comment]
@no-reply Seems like a positive step, thanks!  Not sure about back porting to those minor versions since I am still using AT 0.2.3 in AF 7.x.
