### ISSUE TITLE
Ruby Time is not an http://www.w3.org/2001/XMLSchema#time

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#60]
The ruby Time class has date and time components.

```ruby
> t = Time.new
=> 2014-10-13 12:55:45 -0500
```
But when you serialize to activeTriples, it makes this statement:
```
   <http://projecthydra.org/ns/auth/acl#embargo_release_date> "12:55:45-05:00"^^<http://www.w3.org/2001/XMLSchema#time> .
```

Which loses the Date component.

**Comment by no-reply** [comment]
Looking at this again after all this time, I think it's fine as is. We can always cast the literal manually, and staying aligned with RDF.rb seems best.
