### ISSUE TITLE
Delegating array methods to result doesn't make sense if it's multivalued

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#74]
https://github.com/ActiveTriples/ActiveTriples/blob/711626ccd4bd9a31c2ef19bf4d7a7b2a006d58f1/lib/active_triples/term.rb#L9-Lundefined

because the `resource` method is already returning the first Term.  Perhaps Resource#get_term should handle returning the first item for non multivalued fields instead.

**Comment by no-reply** [comment]
What is the status of this in light of https://github.com/ActiveTriples/ActiveTriples/commit/0ae52d980fa810f50e3e52a7829fce290be62cd0 ?

I'm not sure what is required to recreate the issue in https://github.com/ActiveTriples/ActiveTriples/issues/74#issuecomment-65882684.

For https://github.com/ActiveTriples/ActiveTriples/issues/74#issuecomment-65884308, the status quo is that empty properties return an empty `Relation`:

```ruby
my_source.title || 'blah' # => []     # an empty `Relation`
my_source.title.empty? # => true
my_source.title.count # => 0
```

That interface is increasingly clearly spec'd. If there is some alternative behavior we're looking for, we should decide that soon.

**Comment by no-reply** [comment]
I'm going to go ahead and close this. The array delegation has changed massively in `Relation`; if there's still something to discuss here, let's open a new issue linking back and summarizing the current status.
