### ISSUE TITLE
Should we remove the Indexing module?

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#82]
It's still defining the ActiveFedora module. https://github.com/ActiveTriples/ActiveTriples/blob/16bb42b7e02637e8b387a184f51a57cfd4f90ed1/lib/active_triples/indexing.rb

**Comment by no-reply** [comment]
Yes.

**Comment by terrellt** [comment]
+1

**Comment by no-reply** [comment]
Closed by #83
